server:
    port: 8080
spring:
    application:
        name: payment-system

    datasource:
        url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:payment}
        username: ${DB_USER:root}
        password: ${DB_PASS:password}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    kafka:
        bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
        consumer:
            group-id: payment-group
            auto-offset-reset: earliest
        producer:
            acks: all

    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USER:guest}
        password: ${RABBITMQ_PASS:guest}

